### ISSUE TITLE
[Feature Request] 1x5 size

### ISSUE THREAD

**Issue by Leka1B** [ashutoshgngwr/10-bitClockWidget#127]
The ability to make it a bit smaller would be very nice. I enjoy the widget but the fact that it takes up half the first and half the second row bothers me a little

**Comment by ashutoshgngwr** [comment]
You can resize the widget to take 3x1 cell space now. The default is still 5x2!

**Comment by Leka1B** [comment]
Oh, it's much smaller now... i get the need for padding, but i feel it could squeeze into 5x1 without changing size. Also, the 1x1 size is awesome
