### ISSUE TITLE
Widget size limitation

### ISSUE THREAD

**Issue by protonpony** [ashutoshgngwr/10-bitClockWidget#131]
I'm unable to shrink the widget any smaller than 3x2 on my home screen. I am aware that available dimensions depend heavily on the launcher. That said, can the widget itself be modified to permit smaller sizes?

**Comment by ashutoshgngwr** [comment]
It should shrink to 3x1. Which launcher are you using?

**Comment by protonpony** [comment]
I stand corrected. It does indeed shrink to 3x1. I was actually hoping to attain 2x1 or 2x2. Ideally, any size would be possible even if it wasn't necessarily practical. My Launcher is OneUI 4.1. Thank-you for the prompt response and your contribution to the community. Exactly as it is, your work still deserves 5 stars.
