### ISSUE TITLE
The clock isn't updating unless the app is opened

### ISSUE THREAD

**Issue by MrTheCats** [ashutoshgngwr/10-bitClockWidget#140]

**Comment by ashutoshgngwr** [comment]
Did you try disabling battery usage restrictions for the app?

**Comment by MrTheCats** [comment]
Yes but that did not work, the problem there is only on the F-Droid version the apk work just fine

**Comment by ashutoshgngwr** [comment]
Not sure what's happening here. Both builds should be identical (except that F-Droid uses their build system to build it).
