### ISSUE TITLE
24-h fork request

### ISSUE THREAD

**Issue by neube3** [ashutoshgngwr/10-bitClockWidget#27]
Since there is no other way to contact the author (twitter - cannot message), I chose to write here.

This seems to be the _only_ binary clock app that is available in my country (Poland) both on Google Play store and F-droid that actually displays real time (the other available apps's "seconds" are 1.318359375 actual seconds, so that kind of defeats the point of the clock).

**Would you consider making a fork with 24-hour format? I understand it would not be 10-bit then any more, hence request for a fork for an 11-bitClockWidget**, not a feature strictly for this project. 

It's just one bit more in the hour field, but for me and possibly others it would be a a point for clarity (we are not thinking in 12-h format, "3 o'clock" always means 3 hours after midnight).

**Comment by ashutoshgngwr** [comment]
Hi @neube3! This project is in maintenance mode from my end and I don't actively work on it. But I'll keep this mind for future if I find the time to do so myself. On that note, if you're looking to make the changes yourself, you are free to do so as the project is covered by an open-source license that permits both modification and redistribution.

I'll also be happy to accept changes to add an additional open to toggle between 10-bit (12 hour) and 11-bit (24 hour) format.

**Comment by ashutoshgngwr** [comment]
@neube3 24-hour time format feature is now available for download on GitHub and Play Store.
