### ISSUE TITLE
11 bits in 12 hour mode

### ISSUE THREAD

**Issue by ninomae-inanis** [ashutoshgngwr/10-bitClockWidget#58]
In 12 hour mode during PM hours the widget properly displays 10 bits as intended, however during AM hours a fifth bit is added to the hours section and displays as if 24 hour mode is enabled
![Screenshot_20210627-053259_10-bit Clock Widget](https://user-images.githubusercontent.com/73924307/123538093-5f640500-d709-11eb-8cb6-65dda90da0d1.png)
![Screenshot_20210627-053313_Lawnchair](https://user-images.githubusercontent.com/73924307/123538094-625ef580-d709-11eb-8658-487ccd4267a1.png)
Version 2.0
Android 10

**Comment by ashutoshgngwr** [comment]
@ninomae-inanis I think I know what's causing this. Will fix it ASAP.

**Comment by ashutoshgngwr** [comment]
If you downloaded the widget from the Play Store, you should be able to update it by downloading the [fixed release from GitHub](https://github.com/ashutoshgngwr/10-bitClockWidget/releases/tag/v2.0-1).
