### ISSUE TITLE
Data loss while using the app.

### ISSUE THREAD

**Issue by davirec** [ashutoshgngwr/10-bitClockWidget#72]
When I perform these sequences of events, the dialog on the screen disappears:
1. Open the app;
2. Tap in Dot color (on bit);
3. Change the color using the sliders;
4. Force the pause from the activity and then return to the activity (double rotation).  Note the dialog disappears. note: the pause from activity can be performed in several ways, we suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

The expected behavior is the return to the previous state with the dialog box.

https://user-images.githubusercontent.com/3637419/142345391-06e982ca-2377-42b5-8539-bb8cd84d977e.mp4

Device:
 - Device: Moto G30 with OS: Android 11
 - Device: MI5X with OS: Android 7.1.2
 - Version: 4.0.17

**Comment by ashutoshgngwr** [comment]
Resolved in #73
